name: Farmer
author: [Geik, Amowny, WaterArchery, mehmet-27]
main: xyz.geik.farmer.Main
version: v6-b002
api-version: 1.13
softdepend: [BentoBox, Vault, ASkyBlock, SuperiorSkyblock2, GriefPrevention, FabledSkyBlock]
loadbefore: [AutoPickup, WildStacker]
commands:
  farmer:
    description: Main command of farmer
    aliases: [farm, çiftçi, fm, ciftci]